routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/**
 * Admin routes
 */
Route::namespace('Admin')->group(function () {
    Route::get('admin/login', 'LoginController@showLoginForm')->name('admin.login');
    Route::post('admin/login', 'LoginController@login')->name('admin.login');
    Route::get('admin/logout', 'LoginController@logout')->name('admin.logout');
});
Route::group(['prefix' => 'admin', 'middleware' => ['employee'], 'as' => 'admin.' ], function () {
    Route::namespace('Admin')->group(function () {
        Route::group(['middleware' => ['role:admin|superadmin|clerk, guard:employee']], function () {
            Route::get('/dashboard/{reportBase}', 'DashboardController@index')->name('dashboard');
			Route::get('getOrderData','DashboardController@getOrderData');
			Route::post('change-status','DashboardController@changeStatus')->name('changeStatus');
			Route::post('/productSaleReport', 'DashboardController@productSaleReport');
            Route::namespace('Products')->group(function () {
                Route::resource('products', 'ProductController');
                Route::get('remove-image-product', 'ProductController@removeImage')->name('product.remove.image');
                Route::get('remove-image-thumb', 'ProductController@removeThumbnail')->name('product.remove.thumb');
				Route::get('products/{product}/options', 'ProductController@option')->name('products.options');
            });
            Route::namespace('Customers')->group(function () {
                Route::resource('customers', 'CustomerController');
                Route::resource('customers.addresses', 'CustomerAddressController');
            });
            Route::namespace('Categories')->group(function () {
                Route::resource('categories', 'CategoryController');
                Route::get('remove-image-category', 'CategoryController@removeImage')->name('category.remove.image');
            });
            Route::namespace('Orders')->group(function () {
                Route::resource('orders', 'OrderController');
                Route::resource('order-statuses', 'OrderStatusController');
                Route::get('orders/{id}/invoice', 'OrderController@generateInvoice')->name('orders.invoice.generate');
            });
			Route::get('reports/sale', 'Reports\SalesController@index')->name('sale.index');
			Route::get('reports/sale/export', 'Reports\SalesController@export')->name('sale.export');
			
            Route::resource('addresses', 'Addresses\AddressController');
            Route::resource('countries', 'Countries\CountryController');
            Route::resource('countries.provinces', 'Provinces\ProvinceController');
            Route::resource('countries.provinces.cities', 'Cities\CityController');
            Route::resource('couriers', 'Couriers\CourierController');
            Route::resource('attributes', 'Attributes\AttributeController');
            Route::resource('attributes.values', 'Attributes\AttributeValueController');
            Route::resource('brands', 'Brands\BrandController');
			
			Route::post('order/send-location/{id}', 'Orders\OrderController@sendLocation')->name('order.sendlocation');
			//Route::resource('block', 'Blocks\BlockController');
			
			Route::get('block', 'Blocks\BlockController@index')->name('block.index');
			Route::get('block/{id}/edit', 'Blocks\BlockController@edit')->name('block.edit');
			Route::post('block/store', 'Blocks\BlockController@store')->name('block.store');
			Route::get('block/create', 'Blocks\BlockController@create')->name('block.create');;
			Route::post('block/{id}/update', 'Blocks\BlockController@update')->name('block.update');
			Route::post('block/{id}/destroy', 'Blocks\BlockController@destroy')->name('block.destroy');
			
			//reports
            Route::get('/statsCustomers', 'AdminReportsController@statsCustomers');
            Route::get('/statsProductsPurchased', 'AdminReportsController@statsProductsPurchased');
            Route::get('/statsProductsLiked', 'AdminReportsController@statsProductsLiked');
            Route::get('/productsStock', 'AdminReportsController@productsStock');
            Route::post('/productSaleReport', 'AdminReportsController@productSaleReport');
			
			//coupons
			Route::get('/listingBanners', 'AdminBannersController@listingBanners')->name('listingBanners');
			Route::get('/addBanner', 'AdminBannersController@addBanner')->name('addBanner');
			Route::post('/addNewBanner', 'AdminBannersController@addNewBanner');
			Route::get('/editBanner/{id}', 'AdminBannersController@editBanner');
			Route::post('/updateBanner', 'AdminBannersController@updateBanner');
			Route::post('/deleteBanner/', 'AdminBannersController@deleteBanner');
			 /********* REVIEWS *********/
            Route::get('/reviews', 'AdminReviewsController@index')->name('Reviews');
            Route::post('/review/action', 'AdminReviewsController@action');
			//pages controller
			Route::get('/listingPages', 'AdminPagesController@listingPages')->name('pages');
			Route::get('/addPage', 'AdminPagesController@addPage');
			Route::post('/addNewPage', 'AdminPagesController@addNewPage');
			Route::get('/editPage/{id}', 'AdminPagesController@editPage');
			Route::post('/updatePage', 'AdminPagesController@updatePage');
			Route::get('/pageStatus', 'AdminPagesController@pageStatus');
			//subscribers controller
			Route::get('/subscribers', 'subscribers\AdminSubscribersController@listing')->name('subscribers');
			//zones
			Route::get('/listingZones', 'AdminTaxController@listingZones');
			Route::get('/addZone', 'AdminTaxController@addZone');
			Route::post('/addNewZone', 'AdminTaxController@addNewZone');
			Route::get('/editZone/{id}', 'AdminTaxController@editZone');
			Route::post('/updateZone', 'AdminTaxController@updateZone');
			Route::post('/deleteZone', 'AdminTaxController@deleteZone');

			//tax class
			Route::get('/listingTaxClass', 'AdminTaxController@listingTaxClass');
			Route::get('/addTaxClass', 'AdminTaxController@addTaxClass');
			Route::post('/addNewTaxClass', 'AdminTaxController@addNewTaxClass');
			Route::get('/editTaxClass/{id}', 'AdminTaxController@editTaxClass');
			Route::post('/updateTaxClass', 'AdminTaxController@updateTaxClass');
			Route::post('/deleteTaxClass', 'AdminTaxController@deleteTaxClass');

			//tax rate
			Route::get('/listingTaxRates', 'AdminTaxController@listingTaxRates');
			Route::get('/addTaxRate', 'AdminTaxController@addTaxRate');
			Route::post('/addNewTaxRate', 'AdminTaxController@addNewTaxRate');
			Route::get('/editTaxRate/{id}', 'AdminTaxController@editTaxRate');
			Route::post('/updateTaxRate', 'AdminTaxController@updateTaxRate');
			Route::post('/deleteTaxRate', 'AdminTaxController@deleteTaxRate');

        });
			Route::group(['middleware' => ['role:admin|superadmin, guard:employee']], function () {
            Route::resource('employees', 'EmployeeController');
            Route::get('employees/{id}/profile', 'EmployeeController@getProfile')->name('employee.profile');
            Route::put('employees/{id}/profile', 'EmployeeController@updateProfile')->name('employee.profile.update');
            Route::resource('roles', 'Roles\RoleController');
            Route::resource('permissions', 'Permissions\PermissionController');
        });
    });
});

/**
 * Frontend routes
 */
Auth::routes();
Route::namespace('Auth')->group(function () {
    Route::get('cart/login', 'CartLoginController@showLoginForm')->name('cart.login');
    Route::post('cart/login', 'CartLoginController@login')->name('cart.login');
    Route::get('logout', 'LoginController@logout');
});

Route::namespace('Front')->group(function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::group(['middleware' => ['auth', 'web']], function () {

        Route::namespace('Payments')->group(function () {
            Route::get('bank-transfer', 'BankTransferController@index')->name('bank-transfer.index');
            Route::post('bank-transfer', 'BankTransferController@store')->name('bank-transfer.store');
			Route::get('cash-on-delivery', 'CashOnDeliveryController@index')->name('cash-on-delivery.index');
            Route::post('cash-on-delivery', 'CashOnDeliveryController@store')->name('cash-on-delivery.store');
        });

        Route::namespace('Addresses')->group(function () {
            Route::resource('country.state', 'CountryStateController');
            Route::resource('state.city', 'StateCityController');
        });
		//Route::resource('accounts', 'AccountsController');
        Route::get('accounts', 'AccountsController@index')->name('accounts');
		Route::post('accounts/update', 'AccountsController@update')->name('accounts.update');
		Route::post('accounts/wishlist', 'AccountsController@wishlist')->name('accounts.wishlist');
		Route::get('accounts/order/{orderid}', 'AccountsController@generateInvoice')->name('accounts.invoice');
		Route::post('accounts/order/{orderid}', 'AccountsController@cancelOrder')->name('accounts.cancelorder');
		
        Route::get('checkout', 'CheckoutController@index')->name('checkout.index');
        Route::post('checkout', 'CheckoutController@store')->name('checkout.store');
		
		Route::post('step/{step}', 'CheckoutController@step')->name('checkout.step');
		
        Route::get('checkout/execute', 'CheckoutController@executePayPalPayment')->name('checkout.execute');
        Route::post('checkout/execute', 'CheckoutController@charge')->name('checkout.execute');
        Route::get('checkout/cancel', 'CheckoutController@cancel')->name('checkout.cancel');

app/Http/Controllers/Admin/Attributes/AttributeController.php
<?php

namespace App\Http\Controllers\Admin\Attributes;

use App\Http\Controllers\Controller;
use App\Shop\Attributes\Exceptions\AttributeNotFoundException;
use App\Shop\Attributes\Exceptions\CreateAttributeErrorException;
use App\Shop\Attributes\Exceptions\UpdateAttributeErrorException;
use App\Shop\Attributes\Repositories\AttributeRepository;
use App\Shop\Attributes\Repositories\AttributeRepositoryInterface;
use App\Shop\Attributes\Requests\CreateAttributeRequest;
use App\Shop\Attributes\Requests\UpdateAttributeRequest;
use DB;
class AttributeController extends Controller
{
    private $attributeRepo;

    /**
     * AttributeController constructor.
     * @param AttributeRepositoryInterface $attributeRepository
     */
    public function __construct(AttributeRepositoryInterface $attributeRepository)
    {
        $this->attributeRepo = $attributeRepository;
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $results = $this->attributeRepo->listAttributes();
        $attributes = $this->attributeRepo->paginateArrayResults($results->all());

        return view('admin.attributes.list', compact('attributes'));
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('admin.attributes.create');
    }

    /**
     * @param CreateAttributeRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(CreateAttributeRequest $request)
    {
        $attribute = $this->attributeRepo->createAttribute($request->except('_token'));
        $request->session()->flash('message', 'Create attribute successful!');

        return redirect()->route('admin.attributes.edit', $attribute->id);
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show($id)
    {
        try {
            $attribute = $this->attributeRepo->findAttributeById($id);
            $attributeRepo = new AttributeRepository($attribute);

            return view('admin.attributes.show', [
                'attribute' => $attribute,
                'values' => $attributeRepo->listAttributeValues()
            ]);
        } catch (AttributeNotFoundException $e) {
            request()->session()->flash('error', 'The attribute you are looking for is not found.');

            return redirect()->route('admin.attributes.index');
        }
    }

    /**
     * @param int $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        $attribute = $this->attributeRepo->findAttributeById($id);

        return view('admin.attributes.edit', compact('attribute'));
    }

    /**
     * @param UpdateAttributeRequest $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(UpdateAttributeRequest $request, $id)
    {
        try {
            $attribute = $this->attributeRepo->findAttributeById($id);

            $attributeRepo = new AttributeRepository($attribute);
            $attributeRepo->updateAttribute($request->except('_token'));

            $request->session()->flash('message', 'Attribute update successful!');

            return redirect()->route('admin.attributes.edit', $attribute->id);
        } catch (UpdateAttributeErrorException $e) {
            $request->session()->flash('error', $e->getMessage());

            return redirect()->route('admin.attributes.edit', $id)->withInput();
        }
    }

    /**
     * @param $id
     * @return bool|null
     */
    public function destroy($id)
    {
        $prd = DB::table('attributes')
			->join('attribute_values', 'attribute_values.attribute_id', '=', 'attributes.id')
			->join('attribute_value_product_attribute', 'attribute_value_product_attribute.attribute_value_id', '=', 'attribute_values.id')
			->where('attributes.id', $id)->get();
		if(count($prd) > 0){
			request()->session()->flash('error', 'This attribute is used in product combination.');
			return redirect()->route('admin.attributes.index');
		}else{
			
			$this->attributeRepo->findAttributeById($id)->delete();
			
			request()->session()->flash('message', 'Attribute deleted successfully!');

			return redirect()->route('admin.attributes.index');
		}
    }
}

app/Http/Controllers/Admin/Attributes/AttributeValueController.php
<?php

namespace App\Http\Controllers\Admin\Attributes;

use App\Http\Controllers\Controller;
use App\Shop\Attributes\Repositories\AttributeRepositoryInterface;
use App\Shop\AttributeValues\AttributeValue;
use App\Shop\AttributeValues\Repositories\AttributeValueRepository;
use App\Shop\AttributeValues\Repositories\AttributeValueRepositoryInterface;
use App\Shop\AttributeValues\Requests\CreateAttributeValueRequest;

class AttributeValueController extends Controller
{
    /**
     * @var AttributeRepositoryInterface
     */
    private $attributeRepo;

    /**
     * @var AttributeValueRepositoryInterface
     */
    private $attributeValueRepo;

    /**
     * AttributeValueController constructor.
     * @param AttributeRepositoryInterface $attributeRepository
     * @param AttributeValueRepositoryInterface $attributeValueRepository
     */
    public function __construct(
        AttributeRepositoryInterface $attributeRepository,
        AttributeValueRepositoryInterface $attributeValueRepository
    ) {
        $this->attributeRepo = $attributeRepository;
        $this->attributeValueRepo = $attributeValueRepository;
    }

    public function create($id)
    {
        return view('admin.attribute-values.create', [
            'attribute' => $this->attributeRepo->findAttributeById($id)
        ]);
    }

    /**
     * @param CreateAttributeValueRequest $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(CreateAttributeValueRequest $request, $id)
    {
        $attribute = $this->attributeRepo->findAttributeById($id);

        $attributeValue = new AttributeValue($request->except('_token'));
        $attributeValueRepo = new AttributeValueRepository($attributeValue);

        $attributeValueRepo->associateToAttribute($attribute);

        $request->session()->flash('message', 'Attribute value created');

        return redirect()->route('admin.attributes.show', $attribute->id);
    }

    /**
     * @param $attributeId
     * @param $attributeValueId
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($attributeId, $attributeValueId)
    {
        $attributeValue = $this->attributeValueRepo->findOneOrFail($attributeValueId);

        $attributeValueRepo = new AttributeValueRepository($attributeValue);
        $attributeValueRepo->dissociateFromAttribute();

        request()->session()->flash('message', 'Attribute value removed!');
        return redirect()->route('admin.attributes.show', $attributeId);
    }
}

resources/views/admin/attributes/create.blade.php
@extends('layouts.admin.app')

@section('content')
    <!-- Main content -->
<style>
.checkbox label:after, 
.radio label:after {
    content: '';
    display: table;
    clear: both;
}

.checkbox .cr,
.radio .cr {
    position: relative;
    display: inline-block;
    border: 1px solid #a9a9a9;
    border-radius: .25em;
    width: 1.3em;
    height: 1.3em;
    float: left;
    margin-right: .5em;
}

.radio .cr {
    border-radius: 50%;
}

.checkbox .cr .cr-icon,
.radio .cr .cr-icon {
    position: absolute;
    font-size: .8em;
    line-height: 0;
    top: 50%;
    left: 20%;
}

.radio .cr .cr-icon {
    margin-left: 0.04em;
}

.checkbox label input[type="checkbox"],
.radio label input[type="radio"] {
    display: none;
}

.checkbox label input[type="checkbox"] + .cr > .cr-icon,
.radio label input[type="radio"] + .cr > .cr-icon {
    transform: scale(3) rotateZ(-20deg);
    opacity: 0;
    transition: all .3s ease-in;
}

.checkbox label input[type="checkbox"]:checked + .cr > .cr-icon,
.radio label input[type="radio"]:checked + .cr > .cr-icon {
    transform: scale(1) rotateZ(0deg);
    opacity: 1;
}

.checkbox label input[type="checkbox"]:disabled + .cr,
.radio label input[type="radio"]:disabled + .cr {
    opacity: .5;
}
</style>	
    <section class="content">
        @include('layouts.errors-and-messages')
        <div class="box">
            <form action="{{ route('admin.attributes.store') }}" method="post" class="form">
                <div class="box-body">
                    <div class="row">
                        {{ csrf_field() }}
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="name">Attribute name <span class="text-danger">*</span></label>
                                <input type="text" name="name" id="name" placeholder="Attribute name" class="form-control" value="{!! old('name')  !!}">
                            </div>
                        </div>
						<div class="col-md-12">
							<div class="checkbox">
								<label style="font-size: 1em;padding-left:0px"">
									<input type="checkbox" name="is_configurable" id="is_configurable" value="1">
									<span class="cr"><i class="cr-icon fa fa-check"></i></span>
									Is Configurable
								</label>
							</div>
                        </div>
						<div class="col-md-12">
                           	<div class="checkbox">
								<label style="font-size: 1em;padding-left:0px" >
									<input type="checkbox" name="is_searchable" id="is_searchable" value="1">
									<span class="cr"><i class="cr-icon fa fa-check"></i></span>
									Is Searchable
								</label>
							</div>
                        </div>
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <div class="btn-group">
                        <a href="{{ route('admin.attributes.index') }}" class="btn btn-default">Back</a>
                        <button type="submit" class="btn btn-primary">Create</button>
                    </div>
                </div>
            </form>
        </div>
        <!-- /.box -->
    </section>
    <!-- /.content -->
@endsection

resources/views/admin/attributes/edit.blade.php
@extends('layouts.admin.app')

@section('content')
    <!-- Main content -->
	<style>
.checkbox label:after, 
.radio label:after {
    content: '';
    display: table;
    clear: both;
}

.checkbox .cr,
.radio .cr {
    position: relative;
    display: inline-block;
    border: 1px solid #a9a9a9;
    border-radius: .25em;
    width: 1.3em;
    height: 1.3em;
    float: left;
    margin-right: .5em;
}

.radio .cr {
    border-radius: 50%;
}

.checkbox .cr .cr-icon,
.radio .cr .cr-icon {
    position: absolute;
    font-size: .8em;
    line-height: 0;
    top: 50%;
    left: 20%;
}

.radio .cr .cr-icon {
    margin-left: 0.04em;
}

.checkbox label input[type="checkbox"],
.radio label input[type="radio"] {
    display: none;
}

.checkbox label input[type="checkbox"] + .cr > .cr-icon,
.radio label input[type="radio"] + .cr > .cr-icon {
    transform: scale(3) rotateZ(-20deg);
    opacity: 0;
    transition: all .3s ease-in;
}

.checkbox label input[type="checkbox"]:checked + .cr > .cr-icon,
.radio label input[type="radio"]:checked + .cr > .cr-icon {
    transform: scale(1) rotateZ(0deg);
    opacity: 1;
}

.checkbox label input[type="checkbox"]:disabled + .cr,
.radio label input[type="radio"]:disabled + .cr {
    opacity: .5;
}
</style>
    <section class="content">
        @include('layouts.errors-and-messages')
        <div class="box">
            <form action="{{ route('admin.attributes.update', $attribute->id) }}" method="post" class="form">
                <div class="box-body">
                    <div class="row">
                        {{ csrf_field() }}
                        <input type="hidden" name="_method" value="put">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="name">Attribute name <span class="text-danger">*</span></label>
                                <input type="text" name="name" id="name" placeholder="Attribute name" class="form-control" value="{!! $attribute->name  !!}">
                            </div>
                        </div>
						<div class="col-md-12">
							<div class="checkbox">
								<label style="font-size: 1em;padding-left:0px"">
									<input type="checkbox" name="is_configurable" id="is_configurable" value="1" @if($attribute->is_configurable==1) checked @endif >
									<span class="cr"><i class="cr-icon fa fa-check"></i></span>
									Is Configurable
								</label>
							</div>
                        </div>
						<div class="col-md-12">
                           	<div class="checkbox">
								<label style="font-size: 1em;padding-left:0px" >
									<input type="checkbox" name="is_searchable" id="is_searchable" value="1" @if($attribute->is_searchable==1) checked @endif>
									<span class="cr"><i class="cr-icon fa fa-check"></i></span>
									Is Searchable
								</label>
							</div>
                        </div>
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <div class="btn-group">
                        <a href="{{ route('admin.attributes.index') }}" class="btn btn-default">Back</a>
                        <button type="submit" class="btn btn-primary">Update</button>
                    </div>
                </div>
            </form>
        </div>
        <!-- /.box -->
    </section>
    <!-- /.content -->
@endsection

resources/views/admin/attributes/list.blade.php
@extends('layouts.admin.app')

@section('content')
    <!-- Main content -->
    <section class="content">
    @include('layouts.errors-and-messages')
    <!-- Default box -->
    <div class="box">
        <div class="box-body">
            <h2>Attributes</h2>
            @if($attributes->total() > 0)
            <table class="table">
                <thead>
                    <tr>
                        <td>Attribute name</td>
						<td>Serachable</td>
						<td>Configurable</td>
                        <td></td>
                    </tr>
                </thead>
                <tbody>
                @foreach ($attributes as $attribute)
                    <tr>
                        <td>
                            <a href="{{ route('admin.attributes.show', $attribute->id) }}">{{ $attribute->name }} <strong>({{ $attribute->values->count() }})</strong></a>
                        </td>
						<td>
							@if($attribute->is_searchable==1) Yes @else No @endif
						</td>
						<td>
							@if($attribute->is_configurable==1) Yes @else No @endif
						</td>
						
                        <td>
                            <form action="{{ route('admin.attributes.destroy', $attribute->id) }}" method="post" class="form-horizontal">
                                {{ csrf_field() }}
                                <input type="hidden" name="_method" value="delete">
                                <div class="btn-group">
                                    <a href="{{ route('admin.attributes.values.create', $attribute->id) }}" class="btn btn-default btn-sm"><i class="fa fa-plus"></i> Add values</a>
                                    <a href="{{ route('admin.attributes.edit', $attribute->id) }}" class="btn btn-primary btn-sm"><i class="fa fa-edit"></i> Edit</a>
                                    <button onclick="return confirm('Are you sure?')" type="submit" class="btn btn-danger btn-sm"><i class="fa fa-times"></i> Delete</button>
                                </div>
                            </form>
                        </td>
						
                    </tr>
                @endforeach
                </tbody>
            </table>
            <div class="row">
                <div class="col-md-12">
                    <div class="pull-left">{{ $attributes->links() }}</div>
                </div>
            </div>
                <div class="box-footer">
                    <div class="btn-group">
                        <a class="btn btn-sm btn-primary" href="{{ route('admin.attributes.create') }}"><i class="fa fa-plus"></i> Create attribute</a>
                    </div>
                </div>
            @else
                <p class="alert alert-warning">No attribute yet. <a href="{{ route('admin.attributes.create') }}">Create one</a></p>
            @endif
        </div>
        <!-- /.box-body -->
    </div>
    <!-- /.box -->
    </section>
    <!-- /.content -->
@endsection

resources/views/admin/attributes/show.blade.php
@extends('layouts.admin.app')

@section('content')
    <!-- Main content -->
    <section class="content">
    @include('layouts.errors-and-messages')
    <!-- Default box -->
    <div class="box">
        <div class="box-body">
            <h2>Attributes</h2>
            <table class="table">
                <thead>
                    <tr>
                        <td>Attribute name</td>
                        <td></td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ $attribute->name }}</td>
                        <td></td>
                    </tr>
                </tbody>
            </table>
            @if(!$values->isEmpty())
                <table class="table table-striped" style="margin-left: 35px">
                    <thead>
                        <tr>
                            <td>Attribute Values</td>
                            <td></td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($values as $item)
                            <tr>
                                <td>{{ $item->value }}</td>
                                <td>
                                    <form action="{{ route('admin.attributes.values.destroy', [$attribute->id, $item->id]) }}" class="form-horizontal" method="post">
                                        {{ csrf_field() }}
                                        <input type="hidden" name="_method" value="delete">
                                        <div class="btn-group">
                                            <button onclick="return confirm('Are you sure?')" type="submit" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i> Remove</button>
                                        </div>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            @endif
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            <div class="btn-group">
                <a href="{{ route('admin.attributes.values.create', $attribute->id) }}" class="btn btn-primary btn-sm"><i class="fa fa-plus"></i> Add values</a>
                <a href="{{ route('admin.attributes.index') }}" class="btn btn-default btn-sm">Back</a>
            </div>
        </div>
    </div>
    <!-- /.box -->
    </section>
    <!-- /.content -->
@endsection